import{i as n,S as c}from"./assets/vendor-0fc460d7.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function u(r){const s="https://pixabay.com",o="/api/",i=new URLSearchParams({key:"43954842-86e0551d49d52b31999082e7b",q:r,per_page:"21",image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=`${s}${o}?${i}`;return fetch(e).then(t=>t.json())}function p(r){return r.map(({largeImageURL:s,webformatURL:o,tags:i,likes:e,views:t,comments:a,downloads:l})=>`<li class='images-list'>
            <a class='link-img' href='${s}' download onclick="return false">
            <img class='images' src='${o}' alt='${i}' width='360' height='152'/>
            <ul class='info-wrap'>
            <li class='info-container'> <p class='info-title'>Likes</p> <p class='info-value'>${e}</p> </li>
            <li class='info-container'> <p class='info-title'>Views</p> <p class='info-value'>${t}</p> </li>
            <li class='info-container'> <p class='info-title'>Comments</p> <p class='info-value'>${a}</p> </li>
            <li class='info-container'> <p class='info-title'>Downloads</p> <p class='info-value'>${l}</p> </li>
            </ul>
            </a>
            </li>`).join("")}const f=document.querySelector(".search-form");let m=document.querySelector(".images-box");const d=document.querySelector(".js-loader");f.addEventListener("submit",g);function g(r){r.preventDefault();const s=r.target.elements.query.value.trim();if(!s){n.show({message:"Please enter a search query!",backgroundColor:"#EF4040",messageColor:"#FFF",messageSize:"16px",position:"topRight",maxWidth:"432px"});return}d.classList.add("loader"),u(s).then(o=>{if(o.hits.length===0){n.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#FFF",messageSize:"16px",position:"topRight",maxWidth:"432px"});return}else{const i=p(o.hits);m.innerHTML=i,h.refresh()}}).catch(o=>{console.log(o)}),r.target.elements.query.value=""}let h=new c(".images-box a",{captionDelay:250,captionsData:"alt",captionClass:"text-center"});
//# sourceMappingURL=commonHelpers.js.map
