import{i as n,S as c}from"./assets/vendor-0fc460d7.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();function u(i){const s="https://pixabay.com",o="/api/",r=new URLSearchParams({key:"43954842-86e0551d49d52b31999082e7b",q:i,per_page:"21",image_type:"photo",orientation:"horizontal",safesearch:"true"}),e=`${s}${o}?${r}`;return fetch(e).then(t=>t.json())}function p(i){return i.map(({largeImageURL:s,webformatURL:o,tags:r,likes:e,views:t,comments:a,downloads:l})=>`<li class='images-list'>
            <a class='link-img' href='${s}' download onclick="return false">
            <img class='images' src='${o}' alt='${r}' width='360' height='152'/>
            <ul class='info-wrap'>
            <li class='info-container'> <p class='info-title'>Likes</p> <p class='info-value'>${e}</p> </li>
            <li class='info-container'> <p class='info-title'>Views</p> <p class='info-value'>${t}</p> </li>
            <li class='info-container'> <p class='info-title'>Comments</p> <p class='info-value'>${a}</p> </li>
            <li class='info-container'> <p class='info-title'>Downloads</p> <p class='info-value'>${l}</p> </li>
            </ul>
            </a>
            </li>`).join("")}const m=document.querySelector(".search-form");let f=document.querySelector(".images-box");const d=document.querySelector(".js-loader");m.addEventListener("submit",g);function g(i){i.preventDefault();const s=i.target.elements.query.value.trim();if(!s){n.show({message:"Please enter a search query!",backgroundColor:"#EF4040",messageColor:"#FFF",messageSize:"16px",position:"topRight",maxWidth:"432px"});return}d.classList.add("loader"),u(s).then(o=>{if(o.hits.length===0){n.show({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#FFF",messageSize:"16px",position:"topRight",maxWidth:"432px"});return}else{const r=p(o.hits);f.innerHTML=r,new c(".images-box a",{captionDelay:250,captionsData:"alt",captionClass:"text-center"}).refresh()}}).catch(o=>{console.log(o)}),i.target.elements.query.value=""}
//# sourceMappingURL=commonHelpers.js.map
